log_dataset: 3dig_4miss_tr_subs
missing_s: []
#
#  y\s | 0 1 2
#  ----+-------
#   0  | 0 1 2
#   1  | 3 4 5
#   2  | 6 7 8
#
# subsample_context: {"0": 0.5, "1": 1.0, "2": 0.3, "3": 0.2, "4": 0.4, "5": 0.2}
subsample_context: {}
subsample_train:
    "1": 0.0
    "2": 0.0
    "3": 0.5
    "4": 0.5
    "5": 0.0
    "6": 0.5
    "7": 0.0
    "8": 0.5
