missing_s: []
#
#  y\s | 0 1 2
#  ----+-------
#   0  | 0 1 2
#   1  | 3 4 5
#
subsample_context:
    { "0": 0.5, "1": 1.0, "2": 0.3, "3": 0.2, "4": 0.4, "5": 0.2 }
subsample_train:
    "2": 0.0
    "5": 0.0
